# Generated by Django 4.2.20 on 2025-05-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_color_product_size_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(default='rap', max_length=50),
        ),
    ]
