# Generated by Django 4.2.20 on 2025-05-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.CharField(choices=[('rap', 'Rap Marocain'), ('humour', 'Humour'), ('artistique', 'Artistique'), ('minimal', 'Minimal'), ('message', 'Avec Message')], default='rap', max_length=50),
        ),
    ]
